echo "CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
mkdir cpp_build
cd cpp_build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT} ../
make install
