package:
  name: test_mac_build
  version: 1.0.0

source:
  path: ./

build:
  string: 10d15
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }} # [not osx]
  host:
    - cmake
    - make
