name: Conda Package

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: ""
      - name: Build Package
        shell: bash -l {0}
        run: |
          set -ex
          conda create -n conda_build python=3.8 conda-build -y
          conda activate conda_build
          mkdir conda_pkgs_output
          conda build ./ --output-folder ./conda_pkgs_output
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: conda_pkgs_output/*/test_mac_build-*.tar.bz2
          if-no-files-found: "error"
